### ISSUE TITLE
getArtist Discography returns blank album info

### ISSUE THREAD

**Issue by ar3eh** [caiocinel/SpotifyPrivateAPI#1]
Getting all the artist information seems to work besides for when I try to get details of the discography.

**Comment by caiocinel** [comment]
Can you provide which id are you trying to get?

**Comment by ar3eh** [comment]
It doesn’t seem to work for with any ID. 

Can you give me a snippet/id which works to test?

**Comment by caiocinel** [comment]
Spotify changed API structure, try latest version

**Comment by ar3eh** [comment]
Will do after work, thank you!

**Comment by ar3eh** [comment]
`var artist = await spotify.GetArtist("0NGAZxHanS9e0iNHpR8f2W");

        if(artist == null)
        {
            Console.WriteLine("Artist not found");
            return;
        }

        var items = artist.Data.ArtistUnion.Discography.Singles.Items;
        foreach (SpotifyPrivate.Artist.Item item in items)
        {
            Console.WriteLine(item.Name);
        }`

I'm getting blank returned for the "singles"

**Comment by caiocinel** [comment]
```c#
        for(int i = 0; i < artist.Data.ArtistUnion.Discography.Singles.Items.Count; i++)
        {
            Console.WriteLine("Single " + (i + 1) + ": " + artist.Data.ArtistUnion.Discography.Singles.Items[i].Releases.Items[0].Name);
        }
```

Try it

**Comment by ar3eh** [comment]
Works. Foreach wasn't. Thanks
