### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by ar3eh** [caiocinel/SpotifyPrivateAPI#2]
Does this API have any rate limits?

**Comment by caiocinel** [comment]
Probably, but i've maded 100 thread looping infinitly without no problems, but you can be blocked by Anti-DDoS system in some cases

**Comment by ar3eh** [comment]
Is there somewhere I can message you?

**Comment by caiocinel** [comment]
My discord username is the same that GitHub

**Comment by ar3eh** [comment]
request sent.
